name: Build SecurePad

on:
push:
tags:
- "v*"

permissions:
contents: write

jobs:

build-windows:
runs-on: windows-latest

```
steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-node@v4
    with:
      node-version: 20

  - uses: dtolnay/rust-toolchain@stable

  - name: Install dependencies
    run: npm install

  - name: Build Windows
    run: npm run tauri build

  - name: Upload Windows files
    uses: softprops/action-gh-release@v2
    with:
      files: |
        src-tauri/target/release/bundle/**/*.exe
        src-tauri/target/release/bundle/**/*.msi
```

build-android:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-node@v4
    with:
      node-version: 20

  - uses: dtolnay/rust-toolchain@stable

  - name: Install dependencies
    run: npm install

  - uses: android-actions/setup-android@v3

  - name: Restore keystore
    run: |
      echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > release.keystore

  - name: Init Android
    run: npm run tauri android init

  - name: Build APK
    run: npm run tauri android build

  - name: Sign APK
    run: |
      jarsigner \
      -keystore release.keystore \
      -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
      -keypass ${{ secrets.ANDROID_KEY_PASSWORD }} \
      src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk \
      ${{ secrets.ANDROID_KEY_ALIAS }}

  - name: Upload APK
    uses: softprops/action-gh-release@v2
    with:
      files: |
        src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk
```
        